version: '3.8'

services:

    mysql:
      image: mysql:8.0
      cap_add:
        - SYS_NICE
      environment:
        MYSQL_DATABASE: 'go_db'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - 3306:3306
      volumes:
        - ./mysql_data:/var/lib/mysql
        - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
